apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - image: ubuntu:18.04
        imagePullPolicy: IfNotPresent
        name: ubuntu
        ports:
         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ubuntu
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  